# Generated by Django 3.0.3 on 2020-02-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0002_auto_20200210_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='exit_at',
            field=models.CharField(default='', max_length=31),
            preserve_default=False,
        ),
    ]
